### ISSUE TITLE
fetchSession: fetch is not defined

### ISSUE THREAD

**Issue by allthepies** [jeppe-smith/fpl-api#2]
Hi,
Trying to use the API in a node environment and get the following error when calling fetchSession()

Error handled: ReferenceError: fetch is not defined
    at /var/task/node_modules/fpl-api/src/shared/_fetchSession.ts:18:42
    at step (/var/task/node_modules/fpl-api/dist/shared/_fetchSession.js:33:23)
    at Object.next (/var/task/node_modules/fpl-api/dist/shared/_fetchSession.js:14:53)
    at /var/task/node_modules/fpl-api/dist/shared/_fetchSession.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/task/node_modules/fpl-api/dist/shared/_fetchSession.js:4:12)
    at _fetchSession (/var/task/node_modules/fpl-api/dist/shared/_fetchSession.js:48:12)
    at /var/task/node_modules/fpl-api/src/node/fetchSession.ts:15:29
    at step (/var/task/node_modules/fpl-api/dist/node/fetchSession.js:33:23)
    at Object.next (/var/task/node_modules/fpl-api/dist/node/fetchSession.js:14:53)

**Comment by allthepies** [comment]
This was down to _fetchSession.ts
having
`import "cross-fetch";`
instead of
`import fetch from "cross-fetch";`

Fixed that and I can now access private endpoints.

**Comment by allthepies** [comment]
Rasied a pull request with the fix
#3
